services:
  db:
    image: postgres:17
    container_name: achadinho_postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - apps_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: achadinho_backend
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - apps_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: achadinho_frontend
    expose:
      - "80"
    networks:
      - apps_network
    restart: unless-stopped

volumes:
  db_data:

networks:
  apps_network:
    external: true
