services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
      - ./frontend/assets:/usr/share/nginx/html/assets
    depends_on:
      - backend

  backend:
    build:
      context: ./backend-api
    ports:
      - "8080:8080"
    volumes:
      - ./backend-api:/app
      - ~/.m2:/root/.m2  