# Usa as variáveis de ambiente para configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/achadinho_cupons_db
spring.datasource.username=postgres
spring.datasource.password=8845

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect